name: Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x
    - name: Lint
      run: deno lint
